# Generated by Django 4.2.7 on 2026-04-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_bookingslot_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingSlot',
        ),
    ]
