# Generated by Django 4.2.7 on 2026-04-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_deliverylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='dest_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='dest_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
